version: '3'

networks:
  consul-network:

services:
  consul:
      image: consul
      networks:
          - consul-network
      environment:
        CONSUL_BIND: 0.0.0.0
        CONSUL_CLIENT: 0.0.0.0
      ports:
        - 8503:8500
