version: '3'

networks:
  springcloudexample_consul-network:
    external:
      name: springcloudexample_consul-network


services:
  consumer:
    build: .
    ports:
        - 11092:9092
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - server.port=9092
    external_links:
          - consul:springcloudexample_consul_1
    networks:
         - springcloudexample_consul-network